name: Sync S3
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: 'quinncalzada-cloudresume'
        AWS_ACCESS_KEY_ID: 'AKIAQKGGXRVA2GR4MJGS'
        AWS_SECRET_ACCESS_KEY: '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'
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'website'      # optional: defaults to entire repository